<?php


namespace CCTools\Service;


use CCTools\Facade\RsaUtilFacade;
use Illuminate\Support\ServiceProvider;

class RsaUtilFacadeServiceProvider extends ServiceProvider
{

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->singleton('RsaUtil',function (){
            return new RsaUtilFacade();
        });
    }


}